#!/bin/ash

# include PirateBox shared functionality
. /etc/piratebox.common

# wait for USB disk to show up
pb_usbwait

# check if root password is not set yet
if grep '^root:!:' /etc/passwd >/dev/null
then
  echo "Please set a decent root password..."
  while ! passwd
  do
    echo "Try again!"
  done
  echo "Next time you log in, you must use ssh."
fi

# disable web interface, start PirateBox instead
# Only disable if installed!
if [ -e /etc/init.d/uhttpd ] ; then 
   echo "Stopping uttpd and disable it"
   /etc/init.d/uhttpd stop
   /etc/init.d/uhttpd disable
fi

if [ -e /etc/init.d/luci_fixtime ] ; then
  echo "Stopping luci_fixtime and disable it"
  /etc/init.d/luci_fixtime stop
  /etc/init.d/luci_fixtime disable
fi

if [ -e /etc/init.d/luci_dhcp_migrate ] ; then
  /etc/init.d/luci_dhcp_migrate stop
  /etc/init.d/luci_dhcp_migrate disable
fi

/etc/init.d/piratebox enable

# configure USB, network
/etc/init.d/piratebox setup

# prepare USB partition and install PirateBox
/etc/init.d/piratebox init
/etc/init.d/piratebox update

# Typically this step wrent wrong, so exit if  RC<>0
[ "$?" != "0" ] && echo "Something went wrong during package install on ext" && \
     [ -e /var/lock/opkg.lock_ ] && \
      mv /var/lock/opkg.lock_ /var/lock/opkg.lock  &&  \
      exit 255


# activate config changes
/etc/init.d/firewall restart
/etc/init.d/dnsmasq stop
wifi

# start PirateBox service
/etc/init.d/piratebox start

# give some user feedback
echo
echo "PirateBox wireless SSID: $pb_wireless_ssid"
echo "PirateBox DNS and hostname: $pb_hostname"
echo "  hostname with unique suffix is: "  `uci get system.@system[0].hostname`
echo "PirateBox LAN IP address: $pb_ip"
echo "PirateBox shared directory: $pb_share"
echo
echo "Setup complete, PirateBox started."
echo "You can remove the WAN connection now."
echo "Please reboot your PirateBox now: "
echo "   # reboot "
